[package]
name = "osm-parser"
version = "1.1.0"
license = "MIT"
authors = ["swarkin"]
edition = "2021"
repository = "https://github.com/Swarkin/osm-parser"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
