[package]
name = "osm-parser"
version = "0.3.0"
license = "MIT"
authors = ["swarkin"]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
# Use 64-bit floats
f64 = []
